on:
  push:
    branches:
      - "main"

jobs:
  localhost-check:
    runs-on: ubuntu-latest
    name: "Localhost Check"
    steps:
      - uses: actions/checkout@v3
      - uses: mattsb42/not-grep@master
        with:
          debug: true
            
  publish:
    name: "Build & Publish"
    needs: localhost-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.3.2'
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build 
            